from .DesignChecker import DesignChecker
from .ScoreTemplate import ScoreTemplate
from .anchors import anchors
from .delicatissimo import delicatissimo
from .design_1 import design_1
from .design_2 import design_2
from .design_3 import design_3
from .forty_eighths import forty_eighths
from .glissando_scatto import glissando_scatto
from .graced_tuplets import graced_tuplets
from .monads import monads
from .ovoids import ovoids
from .passepied import passepied
from .rests import rests
from .running import running
from .sixteenths import sixteenths
from .sixty_fourths import sixty_fourths
from .thirds import thirds
from .thirty_seconds import thirty_seconds
from .twentieths import twentieths
from .twenty_eighths import twenty_eighths
from .twenty_fourths import twenty_fourths
from .waves import waves
